TopBeerShop/Controllers/BeersController.cs
using System;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TopBeerShop.Models;
using TopBeerShop.Services.Contracts;
using TopBeerShop.Services.DTOs;
using TopBeerShop.Services.Providers.Contracts;
using TopBeerShop.Web.Models;
using TopBeerShop.Web.Pagination;

namespace TopBeerShop.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService _beerService;
        private readonly IMapper _mapper;
        private readonly IBeerStyleService _beerStyleService;
        private readonly IBreweryService _breweryService;
        private readonly ICountryService _countryService;

        public BeersController(IBeerService beerService, IMapper mapper,
            IBeerStyleService beerStyleService, IBreweryService breweryService, ICountryService countryService)
        {
            _beerService = beerService;
            _mapper = mapper;
            _beerStyleService = beerStyleService;
            _breweryService = breweryService;
            _countryService = countryService;

        }

        // GET: Beers
        public  IActionResult Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["ABVSortParm"] = sortOrder == "ABV" ? "abv_desc" : "ABV";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";


            if (searchString != null) {
                pageNumber = 1;
            }
            else {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;


            var beers = from b in _beerService.GetAllBeers().Select(x => _mapper.Map<BeerViewModel>(x))
                        select b;
            if (!String.IsNullOrEmpty(searchString)) {
                beers = beers.Where(s => s.BeerName.Contains(searchString));

            }
            switch (sortOrder) {
                case "name_desc":
                    beers = beers.OrderByDescending(b => b.BeerName);
                    break;
                case "ABV":
                    beers = beers.OrderBy(b => b.ABV);
                    break;
                case "abv_desc":
                    beers = beers.OrderByDescending(s => s.ABV);
                    break;
                case "Price":
                    beers = beers.OrderBy(b => b.Price);
                    break;
                case "price_desc":
                    beers = beers.OrderByDescending(s => s.Price);
                    break;
                default:
                    beers = beers.OrderBy(s => s.BeerName);
                    break;
            }
            
            int pageSize = 5;
            return View(PaginatedList<BeerViewModel>.Create(beers.AsQueryable(), pageNumber ?? 1, pageSize));
            
        }

        // GET: Beers/Details/5
        public IActionResult Details(int Id)
        {

            try {

                var beer = _beerService.GetBeer(Id);

                if (beer == null) {
                    return NotFound();
                }

                var beerVM = _mapper.Map<BeerViewModel>(beer);

                return View(beerVM);
            }
            catch (Exception) {

                throw new ArgumentException();
            }

        }

        // GET: Beers/Create
        // GET: Beer/Create
        [HttpGet]
        public IActionResult CreateBeer()
        {
            var breweriesDTO = _breweryService.GetAllBreweries();
            var breweriesVM = breweriesDTO.Select(x => _mapper.Map<BreweryViewModel>(x));

            //var countriesDTO = _countryService.GetAllCountries();
            //var countriesVM = countriesDTO.Select(x => _mapper.Map<CountryViewModel>(x));

            var styleDTO = _beerStyleService.GetAllBeerStyles();
            var styleVM = styleDTO.Select(x => _mapper.Map<BeerStyleViewModel>(x));

            ViewData["BreweryId"] = new SelectList(breweriesVM, "BreweryId", "Name");

            ViewData["StyleId"] = new SelectList(styleVM, "Id", "Style");

            return View();
        }

        [HttpPost]
        public IActionResult CreateBeer([Bind("Id,BeerName,ABV,Price,BreweryId,StyleId")] BeerViewModel beerViewModel)
        {
            var beerDTO = _mapper.Map<BeerDTO>(beerViewModel);

            _beerService.CreateBeer(beerDTO);


            return RedirectToAction("Index");
        }




        // GET: Beers/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {

            var breweriesDTO = _breweryService.GetAllBreweries();
            var breweriesVM = breweriesDTO.Select(x => _mapper.Map<BreweryViewModel>(x));
            var styleDTO = _beerStyleService.GetAllBeerStyles();
            var styleVM = styleDTO.Select(x => _mapper.Map<BeerStyleViewModel>(x));

            var beer = _beerService.GetBeer(id);

            var beerVM = _mapper.Map<BeerViewModel>(beer);

            ViewData["BreweryId"] = new SelectList(breweriesVM, "BreweryId", "Name");

            ViewData["StyleId"] = new SelectList(styleVM, "Id", "Style");

            return View(beerVM);


        }

        // POST: Beers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id,BeerName,ABV,Price,BreweryId,StyleId")] BeerViewModel model)
        {

            try {
                var beerDTO = _mapper.Map<BeerDTO>(model);

                _beerService.UpdateBeer(beerDTO);

                var beerVM = _mapper.Map<BeerViewModel>(beerDTO);


                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Index));
            }
            catch (Exception) {

                throw;
            }
        }


        // GET: Beers/Delete/5
        public IActionResult Delete(int id)
        {
            var beerDTO = _beerService.GetBeer(id);

            var beerVM = _mapper.Map<BeerViewModel>(beerDTO);


            return View(beerVM);

        }

        // POST: Countries/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(BeerViewModel beer)
        {

            _beerService.DeleteBeer(beer.BeerId);

            return RedirectToAction(nameof(Index));
        }

        // POST: Beers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public IActionResult DeleteConfirmed(int id)
        //{
        //    var beer = _service.DeleteBeer(id);
        //    return RedirectToAction(nameof(Index));
        //}

        private bool BeerExists(int id)
        {
            try {
                var beer = _beerService.GetBeer(id);

                return true;
            }
            catch (Exception) {

                throw new ArgumentException();
            }
        }
    }
}

TopBeerShop/Controllers/BreweriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TopBeerShop.Data;
using TopBeerShop.Models;
using TopBeerShop.Services.Contracts;
using TopBeerShop.Services.DTOs;
using TopBeerShop.Services.Services;
using TopBeerShop.Web.Models;

namespace TopBeerShop.Web.Controllers
{
    public class BreweriesController : Controller
    {       
        private readonly IBreweryService _breweryService;
        private readonly IMapper _mapper;
        private readonly ICountryService _countryService;

        public BreweriesController(IBreweryService breweryService, IMapper mapper, ICountryService countryService)
        {           
            _breweryService = breweryService;
            _mapper = mapper;
            _countryService = countryService;
        }

        // GET: Breweries
        public IActionResult Index()
        {
            var breweries = _breweryService.GetAllBreweries().Select(x => _mapper.Map<BreweryViewModel>(x));
            return View(breweries);
        }

        // GET: Breweries/Details/5
        public IActionResult Details(int id)
        {
            if (id == null) {
                return NotFound();
            }

            var brewery = _breweryService.GetBrewery(id);             
                
            if (brewery == null) {
                return NotFound();
            }
            var breweryVM = _mapper.Map<BreweryViewModel>(brewery);
            return View(breweryVM);
        }

        // GET: Breweries/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CountryName"] = new SelectList(_countryService.GetAllCountries(), "Name", "Name");
            return View();
        }

        // POST: Breweries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("BreweryId,Name,Website,Address,CountryName,Description")] BreweryViewModel brewery)
        {
            var breweryDTO = _mapper.Map<BreweryDTO>(brewery);

            if (ModelState.IsValid) {
                _breweryService.CreateBrewery(breweryDTO);

                return RedirectToAction(nameof(Index));
            }

            ViewData["Country Name"] = new SelectList(_countryService.GetAllCountries(), "Name", "Name", brewery.CountryName);
            return View(brewery);
        }

        // GET: Breweries/Edit/5
        [Authorize]
        public IActionResult Edit(int id)
        {           
            var breweryDTO = _breweryService.GetBrewery(id);

            if (breweryDTO == null) {
                return NotFound();
            }
            var countriesDTO = _countryService.GetAllCountries();
            var countriesVM = countriesDTO.Select(x => _mapper.Map<CountryViewModel>(x));
            ViewData["CountryName"] = new SelectList(countriesVM, "Name", "Name", breweryDTO.CountryName);

            var breweryVM = _mapper.Map<BreweryViewModel>(breweryDTO);

            return View(breweryVM);
        }

        // POST: Breweries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BreweryViewModel breweryVM)
        {
            try {
                var breweryDTO = _mapper.Map<BreweryDTO>(breweryVM);
                _breweryService.UpdateBrewery(breweryDTO);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception) {

                throw;
            }

        }

        // GET: Breweries/Delete/5
        [Authorize]
        public IActionResult Delete(int id)
        {
            var brewery = _breweryService.GetBrewery(id);

            var breweryVM = _mapper.Map<BreweryViewModel>(brewery);


            return View(breweryVM);
        }

        // POST: Breweries/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _breweryService.DeleteBrewery(id);
            return RedirectToAction(nameof(Index));
        }

        //private bool BreweryExists(int id)
        //{
        //    return _breweryService.Get(e => e.BreweryId == id);
        //}
    }
}

TopBeerShop/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TopBeerShop.Data;
using TopBeerShop.Models;
using TopBeerShop.Services.Providers.Contracts;
using TopBeerShop.Web.Models;

namespace TopBeerShop.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IUserService _userService;
        private readonly IMapper _mapper;


        public UsersController(AppDbContext context, IUserService userService, IMapper mapper)
        {
            _context = context;
            _userService = userService;
            _mapper = mapper;
        }

        // GET: Users       
        public IActionResult Index()
        {
            var users = _userService.GetAllUsers().Select(u => _mapper.Map<UserViewModel>(u));
            return View(users);
        }

        // GET: Users/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            //if (id == null)
            //{
            //    return ;
            //}

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name,IsDeleted,IsBanned,BanDescription,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,IsDeleted,IsBanned,BanDescription,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

TopBeerShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Beers.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style type="text/css">
        body {
            background-image: url(./images/wall.jpg);
            background-size: cover;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Top Beer Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index"> Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Beers</a>
                        <div class="dropdown-menu">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="CreateBeer">Create</a>
                            }
                            <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="Index">List All</a>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Countries</a>
                        <div class="dropdown-menu">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Create">Create</a>
                            }
                            <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">List All</a>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Breweries</a>
                        <div class="dropdown-menu">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Breweries" asp-action="Create">Create</a>
                            }
                            <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Breweries" asp-action="Index">List All</a>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Styles</a>
                        <div class="dropdown-menu">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="BeerStyles" asp-action="Create">Create</a>
                            }
                            <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="BeerStyles" asp-action="Index">List All</a>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Users</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">List All</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
}
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reviews</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Create">Create</a>
                                <a class="dropdown-item"> </a><a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Index">List All</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
}
                </ul>
                    <partial name="_LoginPartial" />
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TopBeerShop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

TopBeerShop/Views/Shared/_SigleBeerPartial.cshtml
@model  BeerViewModel

<div class="col-md-4">
    <img class="align-content-between d-block w-50" img src="~/images/beerIcon.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.BeerName</h5>
        <p class="card-text">@Model.ABV</p>
        <p class="card-text">@Model.Price</p>
        <a asp-area="" asp-controller="Beers" asp-action="Details" asp-route-id="@Model.BeerId" class="btn btn-primary">Find out more</a>
    </div>
</div>

TopBeerShop/Views/Shared/_SingleBreweryPartial.cshtml
@model BreweryViewModel

<div class="col-md-4">
    <img class="align-content-between d-block w-50" img src="~/images/breweries.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.CountryName</p>
        <p class="card-text">@Model.Address</p>
        <p class="card-text">@Model.Website</p>
        <a asp-area="" asp-controller="Breweries" asp-action="Details" asp-route-id="@Model.BreweryId" class="btn btn-primary">Find out more</a>
    </div>
</div>